version: "3"
services:
  nginx:
    image: nginx:1.17.6
    container_name: seo_nginx
    ports:
      - "80:80"
    volumes:
      - ../:/www/seo:cached
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - "php:php"

  php:
    image: wuhuaji/php-fpm:5.6
    depends_on:
      - mysql
    container_name: seo_php
    extra_hosts:
        - seo_plat:192.168.0.9
        - seo_site:192.168.0.9
    links:
      - "mysql:mysql"
      - "redis:redis"
    cap_add:
      - SYS_PTRACE
    ports:
      - "9000:9000"
    volumes:
      - ../:/www/seo:cached
      - ./php.ini:/usr/local/etc/php/php.ini
    working_dir: /www/seo

  mysql:
    image: mysql:5.6.51
    # 兼容 m1 芯片
    platform: linux/amd64
    ports:
      - "3306:3306"
    container_name: seo_mysql
    volumes:
      - ~/dbseo:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: "dA1i3An28D2nC92x(721^1jc"

  redis:
    container_name: seo_redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass PyzRlS2dLwjQuKVr8VWB --appendonly yes
