name: 构建镜像
on:
  push:
    branches: [ "master" ]

jobs:
  build_php_fpm_74:
    runs-on: ubuntu-latest
    steps:
      - name: 获取代码
        uses: actions/checkout@v3

      - name: 登录 docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 构建镜像并推送 docker hub
        run: |
          cd php_fpm_74
          docker build -t wuhuaji/php_fpm_74:latest --platform linux/amd64 ./
          docker push wuhuaji/php_fpm_74:latest
  build_php_fpm_81:
    runs-on: ubuntu-latest
    steps:
      - name: 获取代码
        uses: actions/checkout@v3

      - name: 登录 docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 构建镜像并推送 docker hub
        run: |
          cd php_fpm_81
          docker build -t wuhuaji/php_fpm_81:latest --platform linux/amd64 ./
          docker push wuhuaji/php_fpm_81:latest
